// Star Wars Adventure — original pixel-row sprites. No scraped assets.
// Each string is one row. "." is empty. Frames are baked once and blitted.
// Draw boxes: heroes and stormtroopers 32×32, Grogu 24×24, bosses 40×48.
// Luke and stormtroopers are native 32×32 at scale 1 so the ink stays 1px.
// Dock and Phasma Hangar tiles are native 16×16 at scale 1. Other scales stay integers.

const SPRITE_INK = {
    k: PALETTE.ink,
    h: PALETTE.hull,
    p: PALETTE.panel,
    f: PALETTE.foam,
    b: PALETTE.blue,
    g: PALETTE.green,
    u: PALETTE.purple,
    y: PALETTE.gold,
    d: PALETTE.danger,
    l: PALETTE.lightning,
    v: PALETTE.void,
    o: PALETTE.orange,
    c: PALETTE.fur,
    m: PALETTE.furDeep,
    w: PALETTE.white,
    a: PALETTE.vader,
    e: PALETTE.cloak,
    n: PALETTE.metal,
    s: PALETTE.skin,
    i: PALETTE.hair,
    t: PALETTE.hairDeep,
    j: PALETTE.jacket,
    q: PALETTE.jacketDeep,
    r: PALETTE.chrome,
    x: PALETTE.armor,
    z: PALETTE.stripe,
};

function art(w, lines) {
    const rows = [];
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.length !== w) {
            throw new Error("Sprite row " + i + " is " + line.length + " wide, expected " + w + " [" + line + "]");
        }
        rows.push(line);
    }
    return rows;
}

const ART = {
    wall: art(8, [
        "kkkkkkkk",
        "kppppppk",
        "kpbbbppk",
        "kppppppk",
        "kphhhphk",
        "kppppppk",
        "kpnnnnpk",
        "kkkkkkkk",
    ]),
    floor: art(8, [
        "hhhhhhhh",
        "hpphhhpp",
        "hhhhhhhh",
        "hnnnnnnh",
        "hhhhhhhh",
        "hpphhhpp",
        "hhhhhhhh",
        "hnnnnnnh",
    ]),
    "floor-b": art(8, [
        "hhhhhhhh",
        "hnppppnh",
        "hppppnph",
        "hhhhhhhh",
        "hnppppnh",
        "hppppnph",
        "hhhhhhhh",
        "hbbbbhhh",
    ]),
    "floor-c": art(8, [
        "hhhhhhhh",
        "hphhhpph",
        "hhnnnnhh",
        "hhhhhhhh",
        "hpppphhh",
        "hhhhhhhh",
        "hphhhpph",
        "hhhhhhhh",
    ]),
    "floor-u": art(8, [
        "hhhhhhhh",
        "hpuuuphh",
        "hhhhhhhh",
        "huuuuuuh",
        "hhhhhhhh",
        "hhpuuuph",
        "hhhhhhhh",
        "hbbbbhhh",
    ]),
    "floor-y": art(8, [
        "hhhhhhhh",
        "hyhhhhyh",
        "hhhhhhhh",
        "hnnnnnnh",
        "hhhhhhhh",
        "hhyhhhhy",
        "hhhhhhhh",
        "hyyyyhhh",
    ]),
    viewport: art(8, [
        "..kkkk..",
        ".kvvvvk.",
        "kvvfvvvk",
        "kvvvvvvk",
        "kvvvvfvk",
        "kvfvvvvk",
        ".kvvvvk.",
        "..kkkk..",
    ]),
    "viewport-b": art(8, [
        "..kkkk..",
        ".kvfvvk.",
        "kvvvvvvk",
        "kvvvvfvk",
        "kvfvvvvk",
        "kvvvvvvk",
        ".kvyvvk.",
        "..bbbb..",
    ]),
    pad: art(8, [
        "yhhhhhhy",
        "yhhhhhhy",
        "hh....hh",
        "hh.ff.hh",
        "hh.ff.hh",
        "hh....hh",
        "yhhhhhhy",
        "yhhhhhhy",
    ]),
    hazard: art(8, [
        "hhhhhhhh",
        "hddddhhh",
        "hhddddhh",
        "hhhddddh",
        "hhhhhhhh",
        "ddhhhhdd",
        "hhhhhhhh",
        "hhhhhhhh",
    ]),
    hazard2: art(8, [
        "hhhhhhhh",
        "hhddddhh",
        "hhhddddh",
        "hddddhhh",
        "hhhhhhhh",
        "hhddddhh",
        "hhhhhhhh",
        "hddhhddh",
    ]),
    pillar: art(8, [
        ".kkkkkk.",
        "kkppppkk",
        "kpuuuppk",
        "kpuuuupk",
        "kpuuuupk",
        "kppppppk",
        "kkppppkk",
        ".kkkkkk.",
    ]),
    door: art(8, [
        "kkkkkkkk",
        "kppppppk",
        "kp....pk",
        "kp.ff.pk",
        "kp.ff.pk",
        "kp....pk",
        "kppppppk",
        "kkkkkkkk",
    ]),
    "door-open": art(8, [
        "kkkkkkkk",
        "kp....pk",
        "k......k",
        "k......k",
        "k......k",
        "k......k",
        "kp....pk",
        "kkkkkkkk",
    ]),
    exit: art(8, [
        "kkkkkkkk",
        "kyyyyyyk",
        "ky.dd.yk",
        "ky.dd.yk",
        "ky....yk",
        "kyyyyyyk",
        "kppppppk",
        "kkkkkkkk",
    ]),
    "exit-open": art(8, [
        "kkkkkkkk",
        "kggggggk",
        "kg....gk",
        "kg.ff.gk",
        "kg.ff.gk",
        "kg....gk",
        "kggggggk",
        "kkkkkkkk",
    ]),
    chest: art(8, [
        ".yyyyyy.",
        "kyyyyyyk",
        "kffffffk",
        "kfyyyyfk",
        "kffffffk",
        "kyyyyyyk",
        ".kkkkkk.",
        "........",
    ]),
    switch: art(8, [
        "........",
        ".kkkkkk.",
        ".kppppk.",
        ".kpffpk.",
        ".kppppk.",
        ".kkkkkk.",
        "........",
        "........",
    ]),
    stripe: art(8, [
        "bbbbbbbb",
        "yyyyyyyy",
        "bbbbbbbb",
        "hnnnnnnh",
        "yyyyyyyy",
        "bbbbbbbb",
        "yyyyyyyy",
        "bbbbbbbb",
    ]),
    "stripe-b": art(8, [
        "yyyyyyyy",
        "bbbbbbbb",
        "yfyyyyfy",
        "hnnnnnnh",
        "bfbbbbfb",
        "yyyyyyyy",
        "bbbbbbbb",
        "yyyyyyyy",
    ]),
    pipe: art(8, [
        ".kkkkkk.",
        "knnnnnnk",
        "kbnnnnbk",
        "knbbbbnk",
        "knbbbbnk",
        "kbnnnnbk",
        "knnnnnnk",
        ".kkkkkk.",
    ]),
    heart: art(8, [
        ".gg..gg.",
        "ggg..ggg",
        "gggggggg",
        ".gggggg.",
        "..gggg..",
        "...gg...",
        "........",
        "........",
    ]),
    "heart-empty": art(8, [
        ".pp..pp.",
        "ppp..ppp",
        "pppppppp",
        ".pppppp.",
        "..pppp..",
        "...pp...",
        "........",
        "........",
    ]),
    "lucan-down": art(32, [
        "................................",
        "................................",
        "..........kkkkkkkkkkkk..........",
        ".........kiiiiiiiiiiiik.........",
        ".........kryyyyyyyyyyrk.........",
        ".........kiiiiiiiiiiiik.........",
        ".........kttttttttttttk.........",
        ".........kssssssssssssk.........",
        "........kssssssssssssssk........",
        "........kssbkkssssbkkssk........",
        "........kssssssssssssssk........",
        "........kssssskksssssssk........",
        "........kssssssssssssssk........",
        "........kksssssssssssskk........",
        "...........kjjjjjjjjk...........",
        "......kjjjjjjjjjjjjjjjjjjk......",
        "......kfjk.kjjjjjjjjk.kjjk......",
        "......kjjk.kjjjjqjjjk.kjqk......",
        "......kjjk.kjjjjqjjjk.kjqk......",
        "......kjk..kjjjjqjjjk..kqk......",
        "......kk...kjjjjjjjjk...kk......",
        "...........kyyyyyyyyk...........",
        "...........kkkkkkkkkk...........",
        "..........kjjk....kqqk..........",
        "..........kjjk....kqqk..........",
        "..........kjjj....qqqk..........",
        "..........kjjk....kqqk..........",
        "..........kjjk....kqqk..........",
        "..........kkkk....kkkk..........",
        "...........kk......kk...........",
        "................................",
        "................................",
    ]),
    "lucan-up": art(32, [
        "................................",
        "................................",
        "..........kkkkkkkkkkkk..........",
        ".........kiiiiiiiiiiiik.........",
        ".........kiiiiiiiiiiiik.........",
        ".........kiyiiiiiiiiiyk.........",
        ".........kiiiiiiiiiiiik.........",
        ".........kttttttttttttk.........",
        ".........kttttttttttttk.........",
        ".........kttttttttttttk.........",
        ".........kiiiiiiiiiiiik.........",
        ".........kttttttttttttk.........",
        "........kkttttttttttttkk........",
        "...........kjjjjjjjjk...........",
        "......kjjjjjjjjjjjjjjjjjjk......",
        "......kfjk.kjjjjjjjjk.kjjk......",
        "......kjjk.kjjjjqjjjk.kjqk......",
        "......kjjk.kjjjjqjjjk.kjqk......",
        "......kjk..kjjjjqjjjk..kqk......",
        "......kk...kjjjjjjjjk...kk......",
        "...........kyyyyyyyyk...........",
        "...........kkkkkkkkkk...........",
        "..........kjjk....kqqk..........",
        "..........kjjk....kqqk..........",
        "..........kjjj....qqqk..........",
        "..........kjjk....kqqk..........",
        "..........kjjk....kqqk..........",
        "..........kkkk....kkkk..........",
        "...........kk......kk...........",
        "................................",
        "................................",
        "................................",
    ]),
    "lucan-side": art(32, [
        "................................",
        "................................",
        ".........kkkkkkkkkkkk...........",
        "........kiiiiiiiiiiiik..........",
        "........kryyyyyyyyyyik..........",
        "........kiiiiiiiiiiiiik.........",
        ".........kttttttttttttk.........",
        ".........ksssssssssssk..........",
        "........kssbkkssssssk...........",
        "........kssssssssssssk..........",
        "........ksssssssssssssk.........",
        "........kssssskkssssssk.........",
        ".........ksssssssssssk..........",
        ".........kkssssssssskk..........",
        "...........kjjjjjjjjk...........",
        ".........kjjjjjjjjjjk...........",
        ".......kfjk.kjjjjjjjk...........",
        ".......kjjk..kjjjjqjjk..........",
        ".......kjk...kjjjjqjjk..........",
        ".......kk....kjjjjjjjk..........",
        "............kyyyyyyyyk..........",
        "............kkkkkkkkkk..........",
        "..........kjjk....kqqk..........",
        ".........kjjk.....kqqk..........",
        "........kjj.......kqqk..........",
        ".......kk.........kqqk..........",
        ".......k...........kqk..........",
        "....................kk..........",
        "................................",
        "................................",
        "................................",
        "................................",
    ]),
    "rae-down": art(16, [
        "................",
        ".....ffffff.....",
        "....ffffffff....",
        "....fkffffkf....",
        ".....sffffs.....",
        "......ffff......",
        ".....gggggg.....",
        "....ggfggggg....",
        "....gggggggg....",
        ".....yggggy.....",
        "......gg..gg....",
        "......gg..gg....",
        "......kk..kk....",
        "......kk..kk....",
        "................",
        "................",
    ]),
    "rae-up": art(16, [
        "................",
        ".....ffffff.....",
        "....ffffffff....",
        "....ffffffff....",
        ".....ffffff.....",
        "......ffff......",
        ".....gggggg.....",
        "....gggggggg....",
        "....gggggggg....",
        ".....yggggy.....",
        "......gg..gg....",
        "......gg..gg....",
        "......kk..kk....",
        "......kk..kk....",
        "................",
        "................",
    ]),
    "rae-side": art(16, [
        "................",
        "......ffff......",
        ".....ffffff.....",
        "....fkffffk.....",
        ".....sffffk.....",
        "......fffk......",
        ".....ggggg......",
        "....ggfggg......",
        "....gggggg......",
        ".....yggg.......",
        "......gg........",
        "......gg........",
        "......kk........",
        "......kk........",
        "................",
        "................",
    ]),
    "chewoo-down": art(16, [
        "cc............cc",
        ".c............c.",
        ".cc..........cc.",
        ".cccccccccccccc.",
        "ccmmccccccccmmcc",
        "cckkccccccckkccc",
        ".cccccccccccccc.",
        ".cccyccccycccc..",
        ".cccccccccccccc.",
        "..cccyyyyccccc..",
        "..cccccccccccc..",
        "..cc.cccc.cc....",
        "..cc.cccc.cc....",
        "..kk.kkkk.kk....",
        "................",
        "................",
        "................",
        "................",
    ]),
    "chewoo-up": art(16, [
        "cc............cc",
        ".c............c.",
        ".cc..........cc.",
        ".cccccccccccccc.",
        "cccccccccccccccc",
        "cccccccccccccccc",
        ".cccccccccccccc.",
        ".ccccccccccccc..",
        ".cccccccccccccc.",
        "..cccyyyyccccc..",
        "..cccccccccccc..",
        "..cc.cccc.cc....",
        "..cc.cccc.cc....",
        "..kk.kkkk.kk....",
        "................",
        "................",
        "................",
        "................",
    ]),
    "chewoo-side": art(16, [
        "....cc..........",
        "...c............",
        "................",
        "...cccccccccc...",
        "..cccmmcccccc...",
        "..ccckkccccccc..",
        "..cccccccccccc..",
        "...cccyccccccc..",
        "..cccccccccccc..",
        "..cccyyyycccc...",
        "...cccccccccc...",
        "....cc...cc.....",
        "....cc...cc.....",
        "....kk...kk.....",
        "................",
        "................",
        "................",
        "................",
    ]),
    guard: art(32, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".........kkkkkkkkkkkkkk.........",
        ".........kwwwwwwwwwwwwk.........",
        "........kwwwwwwwwwwwwwwk........",
        ".......kwwwwwwwwwwwwwwwwk.......",
        ".......kfwwwwwwwwwwwwwxwk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        ".......kwwkkkkkkkkkkkkxwk.......",
        ".......kwkkkkkkkkkkkkkkxk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        ".......kwwwkkwwwwkkwwwxwk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        "........kkwwwwwwwwwwwwkk........",
        ".........kkkkkkkkkkkkkk.........",
        ".........kwwwwwwwwwwwwk.........",
        "........kwwwwxxwwxxwwwwk........",
        "........kwwwwwwwwwwwwwxk........",
        "........kwwkkkkkkkkkkxwk........",
        "........kwkxxxxxxxxkwxwk........",
        "........kwwwwwwwwwwwwwxk........",
        ".........kwwwk....kwwwk.........",
        ".........kwwwk....kwwwk.........",
        ".........kxxxk....kwwwk.........",
        ".........kxxk......kwwwk........",
        "..........kk.......kwwwk........",
        "...................kkkkk........",
        "................................",
        "................................",
    ]),
    "guard-step": art(32, [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".........kkkkkkkkkkkkkk.........",
        ".........kwwwwwwwwwwwwk.........",
        "........kwwwwwwwwwwwwwwk........",
        ".......kwwwwwwwwwwwwwwwwk.......",
        ".......kfwwwwwwwwwwwwwxwk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        ".......kwwkkkkkkkkkkkkxwk.......",
        ".......kwkkkkkkkkkkkkkkxk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        ".......kwwwkkwwwwkkwwwxwk.......",
        ".......kwwwwwwwwwwwwwwwxk.......",
        "........kkwwwwwwwwwwwwkk........",
        ".........kkkkkkkkkkkkkk.........",
        ".........kwwwwwwwwwwwwk.........",
        "........kwwwwxxwwxxwwwwk........",
        "........kwwwwwwwwwwwwwxk........",
        "........kwwkkkkkkkkkkxwk........",
        "........kwkxxxxxxxxkwxwk........",
        "........kwwwwwwwwwwwwwxk........",
        "........kwwwk.....kwwwk.........",
        "........kwwwk.....kwwwk.........",
        "........kwwwk.....kxxxk.........",
        ".........kwwwk....kxxk..........",
        ".........kwwwk.....kk...........",
        ".........kkkkk..................",
        "................................",
        "................................",
    ]),
    "boss-chrome": art(10, [
        "..wwwwww..",
        ".wwkkkkww.",
        "wwkwwwwkww",
        ".wwwwwwww.",
        "..yyyyyy..",
        ".wwyyyyww.",
        "wwwwwwwwww",
        "wkwyyyywkw",
        ".wwwwwwww.",
        "..ww..ww..",
        "..kk..kk..",
        "..ww..ww..",
    ]),
    "boss-shadow": art(10, [
        "...uuuu...",
        "..uukkuu..",
        ".uuuuuuuu.",
        ".ukuuuuku.",
        ".uuuuuuuu.",
        ".uhhhhhuu.",
        "uhhhkkhhhu",
        ".uhhkkhhu.",
        "..uu..uu..",
        "..kk..kk..",
        "..hh..hh..",
        "..uu..uu..",
    ]),
    "boss-dark": art(10, [
        "...aaaa...",
        "..aaaaaa..",
        ".aakkkkaa.",
        ".aakyykaa.",
        "..aaaaaa..",
        ".yaaaaaay.",
        "yaayyyaaay",
        ".yaaaaay..",
        "..aaaaaa..",
        "...aa.aa..",
        "...aa.aa..",
        "..aaa.aaa.",
    ]),
    "boss-fallen": art(10, [
        "...ffff...",
        "..ffkkff..",
        ".ffkddkff.",
        ".ffffffff.",
        "..ffddff..",
        ".dffffffd.",
        "ddffyyffdd",
        ".dffyyffd.",
        "..ff..ff..",
        "..kk..kk..",
        "..dd..dd..",
        "..ff..ff..",
    ]),
    "boss-hooded": art(10, [
        "...eeee...",
        "..eeeeee..",
        ".eekkkkee.",
        ".eevvvvvee",
        "..eeeeee..",
        "..ellllee.",
        ".eellllee.",
        "..eeeeee..",
        "...ee.ee..",
        "...ll.ll..",
        "...kk.kk..",
        "...ee.ee..",
    ]),
    little: art(12, [
        ".kk......kk.",
        "kffk....kffk",
        ".kffffffffk.",
        ".kfyyffyyfk.",
        "..ffffffff..",
        "..ffggggff..",
        "...gggggg...",
        "...gggggg...",
        "....g..g....",
        "....k..k....",
        "............",
        "............",
    ]),
    "grogu-face": art(12, [
        ".kk......kk.",
        "kffk....kffk",
        ".kffffffffk.",
        ".kfyyffyyfk.",
        "..kffffffk..",
        "...ffffff...",
        "....ffff....",
        "............",
        "............",
        "............",
        "............",
        "............",
    ]),
    bot: art(16, [
        "................",
        ".....yyyyyy.....",
        "....ypppppy.....",
        "...ypppppppy....",
        "...ypkkkkppy....",
        "...yppffpppy....",
        "...ypfggfppy....",
        "...yppffpppy....",
        "....ypppppy.....",
        ".....yyyyyy.....",
        "......pppp......",
        ".....pppppp.....",
        ".....p....p.....",
        ".....k....k.....",
        "................",
        "................",
    ]),
    "ship-twin": art(20, [
        "........bb..........",
        "......bbbbbb........",
        "....bbbbbbbbbb......",
        "...bbbyyyyyyyybbb...",
        "..bbbbyyppppyybbbb..",
        ".bbbbbyyppppyybbbbb.",
        "bbbbbbyyyyyyyybbbbbb",
        ".bbbbbyyyyyyyybbbbb.",
        "..bbbbyyyyyyyybbbb..",
        "...bbbbkkkkkkbbbb...",
        "....bbkk....kkbb....",
        "....dd......dd......",
    ]),
    "ship-snub": art(12, [
        "....yyyy....",
        "..ffffffff..",
        ".fffpffpfff.",
        ".ffffffffff.",
        "..ffyyyyff..",
        "...ffyyff...",
        "....ffff....",
        ".....kk.....",
        ".....dd.....",
        "............",
        "............",
        "............",
    ]),
    junk: art(8, [
        "..yyyy..",
        ".yppppy.",
        ".pnnnnp.",
        ".pnffnp.",
        ".pnnnnp.",
        ".yppppy.",
        "..dddd..",
        "........",
    ]),
    "junk-b": art(8, [
        "...oo...",
        "..oppo..",
        ".opnnpo.",
        ".pnnnnp.",
        "..pnnnp.",
        "...pp...",
        "....d...",
        "........",
    ]),
    debris: art(8, [
        "..dddd..",
        ".ddnnnd.",
        "dnnddnnd",
        "dnnnnnnd",
        "dnnyynnd",
        ".ddnnnd.",
        "..dddd..",
        "........",
    ]),
    "floor-dock": art(16, [
        "pppppppppppppppp",
        "pppppppppppppppp",
        "bpppbpppbpppbppp",
        "pppppppppppppppp",
        "ppphppppppphpppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "bpppbpppbpppbppp",
        "pppppppppppppppp",
        "ppphppppppphpppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "bpppbpppbpppbppp",
        "pppppppppppppppp",
    ]),
    "floor-dock-b": art(16, [
        "ppbpppbpppbpppbp",
        "pppppppppppppppp",
        "ppppppphppppppph",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "ppbpppbpppbpppbp",
        "pppppppppppppppp",
        "ppppppphppppppph",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "ppbpppbpppbpppbp",
        "pppppppppppppppp",
        "ppppppphppppppph",
        "pppppppppppppppp",
    ]),
    "floor-dock-c": art(16, [
        "ppphppppppphpppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "bpppbpppbpppbppp",
        "pppppppppppppppp",
        "ppphppppppphpppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "bpppbpppbpppbppp",
        "pppppppppppppppp",
        "ppphppppppphpppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
    ]),
    "wall-dock": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kppppppppppppppk",
        "kphhhhhhhhhhhhpk",
        "khpppppppppppphk",
        "khpppppppppppphk",
        "khpppppppppppphk",
        "khbbbbbbbbbbbbhk",
        "khfbfbfbfbfbfbhk",
        "khnnnnnnnnnnnnhk",
        "khpppppppppppphk",
        "khpppppppppppphk",
        "khpppppppppppphk",
        "khpppppppppppphk",
        "kphhhhhhhhhhhhpk",
        "kppppppppppppppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "wall-dock-port": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kppppppppppppppk",
        "kppppkkkkkkppppk",
        "kpppkknnnnkkpppk",
        "kppknnvvvvnnkppk",
        "kpkknvyvvvvnkkpk",
        "kpknvvvvvvvvnkpk",
        "kpknvvvvvvvvnkpk",
        "kpknvvvvvvfvnkpk",
        "kpknvvvvvvvvnkpk",
        "kpkknvvvvvvnkkpk",
        "kppknnvvvvnnkppk",
        "kpppkknnnnkkpppk",
        "kppppkkkkkkppppk",
        "kppppppppppppppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "wall-dock-port-b": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kppppppppppppppk",
        "kppppkkkkkkppppk",
        "kpppkknnnnkkpppk",
        "kppknnvvfvnnkppk",
        "kpkknvvvvvvnkkpk",
        "kpknvvvvvvvvnkpk",
        "kpknvvvvvvvvnkpk",
        "kpknvvvvvvvvnkpk",
        "kpknvyvvvvvvnkpk",
        "kpkknvvvvvvnkkpk",
        "kppknnvvvvnnkppk",
        "kpppkknnnnkkpppk",
        "kppppkkkkkkppppk",
        "kppppppppppppppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "viewport-dock": art(16, [
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppkkkkkkppppp",
        "pppkkbbbbbbkkppp",
        "pppkbbvvvvbbkppp",
        "ppkbbvvvvvvbbkpp",
        "ppkbvyvvvvvvbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbvvvvvvfvbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbbvvvvvvbbkpp",
        "pppkbbvvvvbbkppp",
        "pppkkbbbbbbkkppp",
        "pppppkkkkkkppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
    ]),
    "viewport-dock-b": art(16, [
        "pppppppppppppppp",
        "pppppppppppppppp",
        "pppppkkkkkkppppp",
        "pppkkbbbbbbkkppp",
        "pppkbbvvvvbbkppp",
        "ppkbbvvvfvvbbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbvvvvvvvvbkpp",
        "ppkbbvyvvvvbbkpp",
        "pppkbbvvvvbbkppp",
        "pppkkbbbbbbkkppp",
        "pppppkkkkkkppppp",
        "pppppppppppppppp",
        "pppppppppppppppp",
    ]),
    "glow": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "knnnnnnnnnnnnnnk",
        "kbbbbbbbbbbbbbbk",
        "kbfbfbfbfbfbfbfk",
        "kbbbbbbbbbbbbbbk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "glow-b": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "knnnnnnnnnnnnnnk",
        "kbbbbbbbbbbbbbbk",
        "kfbfbfbfbfbfbfbk",
        "kbbbbbbbbbbbbbbk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kppppppppppppppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "airlock": art(16, [
        "kkkkkkkkkkkkkkkk",
        "khhhhhhhhhhhhhhk",
        "khhhhhhyyhhhhhhk",
        "khhhhyyhhyyhhhhk",
        "khhhyyhhhhyyhhhk",
        "khhyyhhhhhhyyhhk",
        "khhyhhhhhhhhyhhk",
        "khhhhhhhhhhhhhhk",
        "khhhhhhyyhhhhhhk",
        "khhhhyyhhyyhhhhk",
        "khhhyyhhhhyyhhhk",
        "khhyyhhhhhhyyhhk",
        "khhyhhhhhhhhyhhk",
        "khhhhkkkkkkhhhhk",
        "khhhhhhhhhhhhhhk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "airlock-open": art(16, [
        "kkkkkkkkkkkkkkkk",
        "khhhhhhhhhhhhhhk",
        "khhhhhhgghhhhhhk",
        "khhhhgghhgghhhhk",
        "khhhgghhhhgghhhk",
        "khhgghhhhhhgghhk",
        "khhghhhhhhhhghhk",
        "khhhhhhhhhhhhhhk",
        "khhhhhhgghhhhhhk",
        "khhhhgghhgghhhhk",
        "khhhgghhhhgghhhk",
        "khhgghhhhhhgghhk",
        "khhghhhhhhhhghhk",
        "khhhhhhhhhhhhhhk",
        "khhhhhhhhhhhhhhk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "pillar-dock": art(16, [
        "kkkkkkkkkkkkkkkk",
        "kpphppppppphpppk",
        "kphhhppppppphhpk",
        "kphhhppppppphhpk",
        "kphhhppppppphhpk",
        "kphhpkppppkphhpk",
        "kphhpkkkkkkphhpk",
        "kphhpkbbbbkphhpk",
        "kphhpkbfbbkphhpk",
        "kphhpkbbbbkphhpk",
        "kphhpkkkkkkphhpk",
        "kphhhppppppphhpk",
        "kphhhppppppphhpk",
        "kphhhppppppphhpk",
        "kpphppppppphpppk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "floor-hangar": art(16, [
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hkkkkkkkkkhhhhhh",
        "hknnnnnnnkhhhhhh",
        "hknppppphkhhhhhh",
        "hknpfppphkhhhhhh",
        "hknppppphkhhhhhh",
        "hknhhhhhhkhhhhhh",
        "hkkkkkkkkkhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
    ]),
    "floor-hangar-b": art(16, [
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhkkkkkkkkkh",
        "hhhhhhknnnnnnnkh",
        "hhhhhhknpppfphkh",
        "hhhhhhknppppphkh",
        "hhhhhhknhhhhhhkh",
        "hhhhhhkkkkkkkkkh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
    ]),
    "floor-hangar-c": art(16, [
        "knkkkhhhhhhhhhhh",
        "knnnnhhhhhhhhhhh",
        "knpphhhhhhhhhhhh",
        "knhphhhhhhhhhhhh",
        "knhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhk",
        "hhhhhhhhhhhhpnhk",
        "hhhhhhhhhhhhhhhk",
        "hhhhhhhhhhhhhhhk",
        "hhhhhhhhhhhkkkhk",
    ]),
    "hangar-stripe": art(16, [
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "kkkkkkkkkkkkkkkk",
        "kyzzzhhhkyzzzhhh",
        "yzzzhhhkyzzzhhhk",
        "zzzhhhkyzzzhhhky",
        "zzhhhkyzzzhhhkyz",
        "zhhhkyzzzhhhkyzz",
        "hhhkyzzzhhhkyzzz",
        "hhkyzzzhhhkyzzzh",
        "hkyzzzhhhkyzzzhh",
        "kyzzzhhhkyzzzhhh",
        "yzzzhhhkyzzzhhhk",
        "kkkkkkkkkkkkkkkk",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
    ]),
    "hangar-stripe-b": art(16, [
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
        "kkkkkkkkkkkkkkkk",
        "yzzzhhhkyzzzhhhk",
        "zzzhhhkyzzzhhhky",
        "zzhhhkyzzzhhhkyz",
        "zhhhkyzzzhhhkyzz",
        "hhhkyzzzhhhkyzzz",
        "hhkyzzzhhhkyzzzh",
        "hkyzzzhhhkyzzzhh",
        "kyzzzhhhkyzzzhhh",
        "yzzzhhhkyzzzhhhk",
        "zzzhhhkyzzzhhhky",
        "kkkkkkkkkkkkkkkk",
        "hhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhh",
    ]),
    "wall-hangar": art(16, [
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
    ]),
    "wall-hangar-bay": art(16, [
        "kkkkkkkkkkkkkkkk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "kkkkkkkkkkkkkkkk",
        "kyzzkyzkkyzzkyzk",
        "kfzkyzzkkzzkyzyk",
        "kzkyzzkkkzkyzzkk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "wall-hangar-bay-b": art(16, [
        "kkkkkkkkkkkkkkkk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krppnphkkhpphnpk",
        "krnnnnhkkhnnnnnk",
        "krppnphkkhpphnpk",
        "kkkkkkkkkkkkkkkk",
        "kyzzkyzkkyzzkyzk",
        "kyzkyzzkkzzkyzfk",
        "kzkyzzkkkzkyzzkk",
        "kkkkkkkkkkkkkkkk",
    ]),
    "ship-snub-parked": art(72, [
        "........................................................................",
        "........................................................................",
        "..................................kkkk..................................",
        "..................................kxxk..................................",
        ".................................kxxxxk.................................",
        ".................................kxxxxk.................................",
        "...............................kkvvvvvvkk...............................",
        "...............................krvfvvvvnk...............................",
        "...............................krvvrvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krrxxxxxnk...............................",
        "...............zzzzzzzzzzzzzzzkrrrxxxxxnnkzzzzzzzzzzzzzzz...............",
        ".........zzzzzzzzzzzzzzzzzzzzzrrrrxxxxxnnnzzzzzzzzzzzzzzzzzzzzz.........",
        ".....zzzzzzzzzzzzzzzzzzzzzzzzzrrrrxxxxxnnnzzzzzzzzzzzzzzzzzzzzzzzzz.....",
        "...yyyzyyyyyyyyyyyyyyyyyyyyyyyrrrrxxxxxnnnyyyyyyyyyyyyyyyyyyyyyyyzyyy...",
        "...kxyzxxxxxxxxxxxxxxxxxxxxxxxrrrrxxxxxnnnxxxxxxxxxxxxxxxxxxxxxxxzyxk...",
        "...kkyzxxxxxxxxxxxxxxxxxxxxxxxrrrrxxxxxnnnxxxxxxxxxxxxxxxxxxxxxxxzykk...",
        ".....yzxxxxxxxxxnxxxnxxxnxxxxxrrrrxxxxxnnnxxnxxxnxxxnxxxxxxxxxxxxzy.....",
        ".....kkkkxxxxxxxhxxxhxxxhxxxxxrrrrxxxxxnnnxxhxxxhxxxhxxxxxxxxxxkkkk.....",
        ".........knnnnnnnnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnnnnnnnk.........",
        ".........kkkkkknnnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnnkkkkkk.........",
        "...............knnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnk...............",
        "...............kkkkkkkkkkkkkkkrrrrxxxxxnnnkkkkkkkkkkkkkkk...............",
        "..............................krrrxxxxxnnk..............................",
        "..............................krrrxxxxxnnk..............................",
        "...............................krrxxxxxnk...............................",
        "...............................krrxxxxxnk...............................",
        "................................kyzxxzyk................................",
        "................................kzxxxxyk................................",
        ".................................kkkkkk.................................",
        "........................................................................",
        "........................................................................",
        "........................................................................",
    ]),
    "ship-snub-parked-b": art(72, [
        "........................................................................",
        "........................................................................",
        "..................................kkkk..................................",
        "..................................kxxk..................................",
        ".................................kxxxxk.................................",
        ".................................kxxxxk.................................",
        "...............................kkvvvvvvkk...............................",
        "...............................krvvfvvvnk...............................",
        "...............................krvvrvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krvvvvvvnk...............................",
        "...............................krrxxxxxnk...............................",
        "...............zzzzzzzzzzzzzzzkrrrxxxxxnnkzzzzzzzzzzzzzzz...............",
        ".........zzzzzzzzzzzzzzzzzzzzzrrrrxxxxxnnnzzzzzzzzzzzzzzzzzzzzz.........",
        ".....zzzzzzzzzzzzzzzzzzzzzzzzzrrrrxxxxxnnnzzzzzzzzzzzzzzzzzzzzzzzzz.....",
        "...yyyzyyyyyyyyyyyyyyyyyyyyyyyrrrrxxxxxnnnyyyyyyyyyyyyyyyyyyyyyyyzyyy...",
        "...kxyzxxxxxxxxxxxxxxxxxxxxxxxrrrrxxxxxnnnxxxxxxxxxxxxxxxxxxxxxxxzyxk...",
        "...kkyzxxxxxxxxxxxxxxxxxxxxxxxrrrrxxxxxnnnxxxxxxxxxxxxxxxxxxxxxxxzykk...",
        ".....yzxxxxxxxxxnxxxnxxxnxxxxxrrrrxxxxxnnnxxnxxxnxxxnxxxxxxxxxxxxzy.....",
        ".....kkkkxxxxxxxhxxxhxxxhxxxxxrrrrxxxxxnnnxxhxxxhxxxhxxxxxxxxxxkkkk.....",
        ".........knnnnnnnnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnnnnnnnk.........",
        ".........kkkkkknnnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnnkkkkkk.........",
        "...............knnnnnnnnnnnnnnrrrrxxxxxnnnnnnnnnnnnnnnnnk...............",
        "...............kkkkkkkkkkkkkkkrrrrxxxxxnnnkkkkkkkkkkkkkkk...............",
        "..............................krrrxxxxxnnk..............................",
        "..............................krrrxxxxxnnk..............................",
        "...............................krrxxxxxnk...............................",
        "...............................krrxxxxxnk...............................",
        "................................kyzxxzyk................................",
        "................................kzxxxxyk................................",
        ".................................kkkkkk.................................",
        "........................................................................",
        "........................................................................",
        "........................................................................",
    ]),
};

const SPRITE_SCALE = {
    wall: 2, floor: 2, "floor-b": 2, "floor-c": 2, "floor-u": 2, "floor-y": 2,
    viewport: 2, "viewport-b": 2, pad: 2,
    hazard: 2, hazard2: 2, pillar: 2, door: 2, "door-open": 2,
    exit: 2, "exit-open": 2, chest: 2, switch: 2, stripe: 2, "stripe-b": 2, pipe: 2,
    heart: 2, "heart-empty": 2,
    "lucan-down": 1, "lucan-up": 1, "lucan-side": 1,
    "rae-down": 2, "rae-up": 2, "rae-side": 2,
    "chewoo-down": 2, "chewoo-up": 2, "chewoo-side": 2,
    guard: 1, "guard-step": 1,
    "floor-dock": 1, "floor-dock-b": 1, "floor-dock-c": 1,
    "wall-dock": 1, "wall-dock-port": 1, "wall-dock-port-b": 1,
    "viewport-dock": 1, "viewport-dock-b": 1,
    glow: 1, "glow-b": 1, airlock: 1, "airlock-open": 1, "pillar-dock": 1,
    "floor-hangar": 1, "floor-hangar-b": 1, "floor-hangar-c": 1,
    "hangar-stripe": 1, "hangar-stripe-b": 1,
    "wall-hangar": 1, "wall-hangar-bay": 1, "wall-hangar-bay-b": 1,
    "hangar-exit": 1, "hangar-exit-open": 1,
    "viewport-hangar": 1, "viewport-hangar-b": 1,
    "ship-snub-parked": 1, "ship-snub-parked-b": 1,
    "boss-chrome": 4, "boss-shadow": 4, "boss-dark": 4, "boss-fallen": 4, "boss-hooded": 4,
    little: 2,
    "grogu-face": 2,
    bot: 2,
    "ship-twin": 2,
    "ship-snub": 2,
    junk: 2,
    "junk-b": 2,
    debris: 2,
};

const Sprites = {
    cache: {},

    build() {
        const keys = Object.keys(ART);
        for (let i = 0; i < keys.length; i++) {
            const key = keys[i];
            this.cache[key] = bakeSprite(ART[key], SPRITE_SCALE[key] || 2);
        }
    },

    draw(ctx, key, x, y, flip) {
        const canvas = this.cache[key];
        if (!canvas) return;
        const w = canvas.width;
        const h = canvas.height;
        ctx.imageSmoothingEnabled = false;
        if (flip) {
            ctx.save();
            ctx.translate(Math.round(x), Math.round(y));
            ctx.scale(-1, 1);
            ctx.drawImage(canvas, Math.round(-w / 2), Math.round(-h / 2));
            ctx.restore();
        } else {
            ctx.drawImage(canvas, Math.round(x - w / 2), Math.round(y - h / 2));
        }
    },

    heroKey(id, facing) {
        if (Math.abs(facing.x) > Math.abs(facing.y)) return id + "-side";
        if (facing.y < 0) return id + "-up";
        return id + "-down";
    },

    heroFlip(facing) {
        return Math.abs(facing.x) > Math.abs(facing.y) && facing.x < 0;
    },

    drawBlade(ctx, x, y, facing, length, color, wide) {
        const ang = Math.atan2(facing.y, facing.x);
        const x1 = x + Math.cos(ang) * 8;
        const y1 = y + Math.sin(ang) * 8;
        const x2 = x + Math.cos(ang) * length;
        const y2 = y + Math.sin(ang) * length;
        ctx.save();
        ctx.lineCap = "round";
        ctx.strokeStyle = color;
        ctx.globalAlpha = 0.35;
        ctx.lineWidth = (wide || 3) + 5;
        ctx.beginPath();
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
        ctx.globalAlpha = 1;
        ctx.lineWidth = wide || 3;
        ctx.stroke();
        ctx.strokeStyle = PALETTE.foam;
        ctx.lineWidth = 1;
        ctx.stroke();
        ctx.restore();
    },

    drawSwing(ctx, x, y, facing, range, color, swing, dur) {
        const ang = Math.atan2(facing.y, facing.x);
        const spanTime = dur || 0.22;
        const along = 1 - Math.max(0, Math.min(1, swing / spanTime));
        const span = 1.7;
        const a0 = ang - span * 0.62 + along * span;
        const a1 = a0 + span * 0.55;
        const radius = Math.max(18, range * 0.86);
        ctx.save();
        ctx.lineCap = "round";
        ctx.strokeStyle = color;
        ctx.globalAlpha = 0.28;
        ctx.lineWidth = 14;
        ctx.beginPath();
        ctx.arc(x, y, radius, a0, a1);
        ctx.stroke();
        ctx.globalAlpha = 0.95;
        ctx.lineWidth = 5;
        ctx.stroke();
        ctx.strokeStyle = PALETTE.foam;
        ctx.lineWidth = 2;
        ctx.stroke();
        const tip = a0 + (a1 - a0) * 0.85;
        const tx = x + Math.cos(tip) * radius;
        const ty = y + Math.sin(tip) * radius;
        ctx.globalAlpha = 1;
        ctx.fillStyle = PALETTE.foam;
        ctx.beginPath();
        ctx.arc(tx, ty, 5, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = color;
        ctx.beginPath();
        ctx.arc(tx, ty, 3, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
    },

    drawAim(ctx, x, y, facing, color, strong) {
        const fx = facing && facing.x ? facing.x : 0;
        const fy = facing && facing.y ? facing.y : 0;
        const ang = fx || fy ? Math.atan2(fy, fx) : Math.PI / 2;
        const dist = strong ? 36 : 26;
        ctx.save();
        ctx.translate(x, y);
        ctx.rotate(ang);
        ctx.strokeStyle = PALETTE.foam;
        ctx.globalAlpha = strong ? 1 : 0.85;
        ctx.lineWidth = strong ? 3 : 2;
        ctx.beginPath();
        ctx.moveTo(12, 0);
        ctx.lineTo(dist - 4, 0);
        ctx.stroke();
        ctx.translate(dist, 0);
        ctx.fillStyle = color;
        ctx.globalAlpha = 1;
        ctx.beginPath();
        ctx.moveTo(10, 0);
        ctx.lineTo(-8, 7);
        ctx.lineTo(-4, 0);
        ctx.lineTo(-8, -7);
        ctx.closePath();
        ctx.fill();
        ctx.fillStyle = PALETTE.foam;
        ctx.fillRect(-2, -1, 7, 2);
        ctx.restore();
    },
};

function bakeSprite(rows, scale) {
    const h = rows.length;
    const w = rows[0].length;
    const canvas = document.createElement("canvas");
    canvas.width = w * scale;
    canvas.height = h * scale;
    const g = canvas.getContext("2d");
    g.imageSmoothingEnabled = false;
    for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
            const ch = rows[y][x];
            if (ch === "." || !SPRITE_INK[ch]) continue;
            g.fillStyle = SPRITE_INK[ch];
            g.fillRect(x * scale, y * scale, scale, scale);
        }
    }
    return canvas;
}
